all: test

main: 
	@echo "Executing main.py with python3"
	python3 main.py $(ARGS)


test:
	@echo "Executing test.py with python3"
	python3 main.py "5 * X^0 + 4 * X^1 - 9.3 * X^2 = 1 * X^0"
	python3 main.py "5 * X^0 + 4 * X^1 = 4 * X^0"
	python3 main.py "5 * X^0 + 4 * X^1 = 4 * X^0 + 7 * X^1"